### ISSUE TITLE
Image in documentation

### ISSUE THREAD

**Issue by davidnewcomb** [alkasm/magicwand#2]
Can you add a screenshot of what the `SelectionWindow` actually shows.
The only picture I could find was on http://reynoldsalexander.com/ but it's far too small to see what is happening.

**Comment by alkasm** [comment]
Thanks for the suggestion, it is a good one! I am current revamping some old projects (including this one) and will include an example screen shot. I did the same when I revamped my old colorspace filter project today, mostly because I was thinking about it from you suggesting it: https://github.com/alkasm/colorfilters

**Comment by alkasm** [comment]
Fixed with https://github.com/alkasm/magicwand/pull/3
