### ISSUE TITLE
qt support

### ISSUE THREAD

**Issue by evgenygamza** [alkasm/magicwand#4]
Hello!
Got issue with OpenCV library. I've got version 4.5.1.48 on my 3.6 python.
When i'm trying to execute example code, python returns following error:

cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6uw63ony\opencv\modules\highgui\src\window.cpp:567: error: (-213:The function/feature is not implemented) The library is compiled without QT support in function 'cv::displayStatusBar'
 
 Please, help. Where can I download correct opencv compilation?

**Comment by alkasm** [comment]
Hey, sorry you can't use it with your installation! 

I believe the `opencv-python` Python package on PyPI is not built with Qt support for Windows. Note on the [package index page](https://pypi.org/project/opencv-python/) under the Licensing section, it specifically states:

> Non-headless Linux and MacOS wheels ship with Qt 5 licensed under the LGPLv3.

which doesn't directly state but implies the Windows wheels are not built with Qt support. 

I'm not particularly familiar with OpenCV installations on Windows (or any software on Windows, really), but you for sure can compile OpenCV yourself with Qt support. I'm not sure if a pre-compiled library exists with Qt for your platform or not. You can try the conda distributions of OpenCV, there are ones both under the anaconda and conda-forge channels. 

Qt does have a tutorial on their site for setting up OpenCV with Qt on Windows: https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows

I considered giving some other input method instead of a trackbar (e.g. command line), but this application also requires mouse callbacks to be registered, which I believe requires Qt, so there's not much point.

**Comment by Wandergin** [comment]
Hi @alkasm, well done on the package! On a mac os distribution, it also doesn't seem to support qt, any insights on how to make it work?

I've tried:
1. Installing opencv-contrib-python, which should support qt.
2. Changing the cv.displayStatusBar to cv.displayOverlay to cross-check whether any of those are supported (none).
3. (EDIT) Downloading QT installer from here (https://download.qt.io/archive/qt/4.8/4.8.7/). The installer does not work with 64-bit architecture (Monterey).

Ended up removing cv.displayStatusBar altogether, although I feel like missing a bit of functionality now, printing it out instead.

Maybe you could point me towards an opencv distribution that has qt? Or otherwise, I have found pyQT libraries, which seem to be the wrappers for the original qt, any idea how to link them up with this project?

Many thanks. :)

**Comment by Wandergin** [comment]
> Hey, sorry you can't use it with your installation!
> 
> I believe the `opencv-python` Python package on PyPI is not built with Qt support for Windows. Note on the [package index page](https://pypi.org/project/opencv-python/) under the Licensing section, it specifically states:
> 
> > Non-headless Linux and MacOS wheels ship with Qt 5 licensed under the LGPLv3.
> 
> which doesn't directly state but implies the Windows wheels are not built with Qt support.

Also I think they've removed Mac OS support: "Non-headless Linux wheels ship with [Qt 5](http://doc.qt.io/qt-5/lgpl.html) licensed under the [LGPLv3](http://www.gnu.org/licenses/lgpl-3.0.html)." https://pypi.org/project/opencv-python/

**Comment by alkasm** [comment]
@Wandergin that's a bummer that they've removed Qt from the Python installation in newer builds for macOS. To get something working, you might be able to install an older version of opencv-python which did come with Qt support, or build OpenCV from source with Qt support.

I'm not sure exactly when they removed support, but the documentation change which showed that macOS support for Qt was removed was in this PR: https://github.com/opencv/opencv-python/pull/515

I think I would have to rewrite the interactive application in another framework, rather than using the functions that ship with OpenCV (since they're not supported under all/most installations). I could do this with pyqt (unofficial bindings), pyside (official bindings), tkinter, or some other GUI framework (potentially a web app)?

However, this project mostly exists as tutorial for `floodFill` but also for OpenCV's high GUI module, so I'm not totally sure whether I should or shouldn't change it.
